-- Warning: You can generate script only for one table/view at a time in your Free plan 
-- 
-- ************************* SqlDBM: PostgreSQL *************************
-- ********** Generated by SqlDBM: Sales by rusakltd **********

-- ************************************** Calendar
CREATE TABLE Calendar
(
 ship_date  date NOT NULL,
 order_date date NOT NULL,
 year       int4range NOT NULL,
 quarter    varchar(5) NOT NULL,
 month      int4range NOT NULL,
 week       int4range NOT NULL,
 week_day   int4range NOT NULL,
 CONSTRAINT PK_4 PRIMARY KEY ( ship_date, order_date )
);

-- ************************************** Geography
CREATE TABLE Geography
(
 geo_id       NOT NULL,
 country     varchar(25) NOT NULL,
 city        varchar(25) NOT NULL,
 "state"     varchar(25) NOT NULL,
 region      varchar(9) NOT NULL,
 postal_code int NOT NULL,
 CONSTRAINT PK_5 PRIMARY KEY ( geo_id )
);

-- ************************************** Product
CREATE TABLE Product
(
 product_id   int NOT NULL,
 category     varchar(50) NOT NULL,
 subcategory  varchar(50) NOT NULL,
 segment      varchar(50) NOT NULL,
 product_name varchar(250) NOT NULL,
 CONSTRAINT PK_2 PRIMARY KEY ( product_id )
);

-- ************************************** Shipping
CREATE TABLE Shipping
(
 ship_id   int NOT NULL,
 ship_mode varchar(50) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( ship_id )
);


-- ************************************** Sales
CREATE TABLE Sales
(
 row_id      NOT NULL,
 order_id    NOT NULL,
 sales       NOT NULL,
 quantity    NOT NULL,
 discount    NOT NULL,
 profit      NOT NULL,
 geo_id      NOT NULL,
 order_date date NOT NULL,
 ship_id    int NOT NULL,
 product_id int NOT NULL,
 ship_date  date NOT NULL,
 CONSTRAINT PK_3 PRIMARY KEY ( row_id ),
 CONSTRAINT FK_1 FOREIGN KEY ( geo_id ) REFERENCES Geography ( geo_id ),
 CONSTRAINT FK_2 FOREIGN KEY ( ship_date, order_date ) REFERENCES Calendar ( ship_date, order_date ),
 CONSTRAINT FK_3 FOREIGN KEY ( ship_id ) REFERENCES Shipping ( ship_id ),
 CONSTRAINT FK_4 FOREIGN KEY ( product_id ) REFERENCES Product ( product_id )
);

CREATE INDEX FK_1 ON Sales
(
 geo_id
);

CREATE INDEX FK_2 ON Sales
(
 order_date,
 ship_date
);

CREATE INDEX FK_3 ON Sales
(
 ship_id
);

CREATE INDEX FK_4 ON Sales
(
 product_id
);
